name: Deploy

on:
  push:
    tags:
      - '*'
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: chiubi-cloud-linux
        if-no-files-found: error
        path: |
          target/release/chiubi-cloud*
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: ncipollo/release-action@v1.8.10
      with:
        artifacts: chiubi-cloud-linux
        draft: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

